-- SHOW TABLES CONTENTS
SELECT * FROM users;
SELECT * FROM categories;
SELECT * FROM posts;
SELECT * FROM categories_posts;
SELECT * FROM posts_votes;
SELECT * FROM comments;
SELECT * FROM comments_votes;
SELECT * FROM sessions;
